import { NextResponse } from 'next/server'
import { requireAdminContext } from '@/lib/api/auth'
import { createSupabaseAdminClient } from '@/lib/supabase/admin'
import { recordAuditLog } from '@/lib/audit'

function escapePdfText(value: string) {
  return value.replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)')
}

function simplePdf(lines: string[]) {
  const body = lines.slice(0, 32).map((line, index) => `BT /F1 11 Tf 48 ${760 - index * 20} Td (${escapePdfText(line)}) Tj ET`).join('\n')
  const stream = `${body}\n`
  const objects = [
    '1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj',
    '2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj',
    '3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj',
    '4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj',
    `5 0 obj << /Length ${stream.length} >> stream\n${stream}endstream endobj`,
  ]
  let offset = '%PDF-1.4\n'.length
  const xref = objects.map((object) => {
    const current = offset
    offset += object.length + 1
    return current
  })
  const content = `%PDF-1.4\n${objects.join('\n')}\n`
  const xrefStart = content.length
  const xrefRows = xref.map((entry) => `${String(entry).padStart(10, '0')} 00000 n `).join('\n')
  return Buffer.from(`${content}xref\n0 6\n0000000000 65535 f \n${xrefRows}\ntrailer << /Size 6 /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`)
}

export async function POST(_request: Request, { params }: { params: Promise<{ id: string }> }) {
  const context = await requireAdminContext()
  if ('response' in context) return context.response
  const { id } = await params
  const admin = createSupabaseAdminClient()

  const { data: inspection } = await admin
    .from('inspections')
    .select('id,plot_id,property_id,summary,arrival_latitude,arrival_longitude,arrival_accuracy_meters,arrival_distance_meters,properties(title,address,city,owner_profile_id),plots(plot_number,location),employees(profile_id,profiles(full_name,email))')
    .eq('id', id)
    .maybeSingle()

  if (!inspection) {
    return NextResponse.json({ ok: false, error: { code: 'INSPECTION_NOT_FOUND', message: 'Inspection was not found.' } }, { status: 404 })
  }

  const property = Array.isArray(inspection.properties) ? inspection.properties[0] : inspection.properties
  const plot = Array.isArray(inspection.plots) ? inspection.plots[0] : inspection.plots
  const employee = Array.isArray(inspection.employees) ? inspection.employees[0] : inspection.employees
  const profile = Array.isArray(employee?.profiles) ? employee?.profiles[0] : employee?.profiles
  const ownerId = property?.owner_profile_id

  const { data: photos } = await admin.from('inspection_photos').select('id,direction,captured_at,latitude,longitude,accuracy_meters').eq('inspection_id', id).order('created_at')
  const reportPath = `${ownerId || 'owner'}/${id}/inspection-report-${Date.now()}.pdf`
  const pdf = simplePdf([
    'PlotKare Inspection Report',
    `Report date: ${new Date().toLocaleString('en-IN')}`,
    `Inspection: ${id}`,
    `Plot: ${plot?.plot_number || plot?.location || 'Plot pending'}`,
    `Address: ${[property?.title, property?.address, property?.city].filter(Boolean).join(', ') || 'Address pending'}`,
    `Agent: ${profile?.full_name || profile?.email || 'PlotKare field agent'}`,
    `GPS arrival: ${inspection.arrival_latitude ?? 'pending'}, ${inspection.arrival_longitude ?? 'pending'}`,
    `GPS accuracy: ${inspection.arrival_accuracy_meters ?? 'pending'}`,
    `Distance check: ${inspection.arrival_distance_meters ?? 'pending'} meters`,
    `Summary: ${inspection.summary || 'Field inspection approved by PlotKare.'}`,
    `Evidence photos: ${(photos ?? []).length}`,
    ...((photos ?? []).map((photo) => `${photo.direction}: ${photo.captured_at || 'time pending'} ${photo.latitude || ''}, ${photo.longitude || ''}`)),
    'This report was generated by PlotKare based on field evidence captured during inspection.',
  ])

  const { error: uploadError } = await admin.storage.from('inspection-reports').upload(reportPath, pdf, {
    contentType: 'application/pdf',
    upsert: true,
  })
  if (uploadError) {
    return NextResponse.json({ ok: false, error: { code: 'REPORT_UPLOAD_FAILED', message: 'Could not upload the inspection report.' } }, { status: 400 })
  }

  await admin.from('inspections').update({
    workflow_step: 'approved',
    reviewed_at: new Date().toISOString(),
    approved_at: new Date().toISOString(),
    report_path: reportPath,
  }).eq('id', id)

  const reportUpdate = {
    owner_id: ownerId,
    plot_id: inspection.plot_id ?? null,
    inspection_id: id,
    month: new Intl.DateTimeFormat('en-IN', { month: 'long', year: 'numeric' }).format(new Date()),
    agent_name: profile?.full_name || profile?.email || 'PlotKare field agent',
    finding: inspection.summary || 'Inspection approved by PlotKare.',
    status: 'Completed',
    report_file_path: reportPath,
    reviewed_by: context.user.id,
    approved_at: new Date().toISOString(),
    released_at: new Date().toISOString(),
    delivery_status: 'dashboard_ready',
    email_delivery_status: 'not_configured',
  }

  const { data: existingReport } = await admin.from('inspection_reports').select('id').eq('inspection_id', id).limit(1).maybeSingle()
  if (existingReport?.id) {
    await admin.from('inspection_reports').update(reportUpdate).eq('id', existingReport.id)
  } else {
    await admin.from('inspection_reports').insert(reportUpdate)
  }

  if (ownerId) {
    await admin.from('notifications').insert({
      recipient_id: ownerId,
      actor_id: context.user.id,
      title: 'Inspection report ready',
      message: 'Your PlotKare inspection report is available in your dashboard.',
      category: 'inspection',
      metadata: { inspection_id: id, report_path: reportPath },
    })
  }

  await recordAuditLog({ actorId: context.user.id, action: 'inspection_approved', entityType: 'inspections', entityId: id, metadata: { report_path: reportPath } })
  return NextResponse.json({ ok: true, reportPath })
}
