import { PDFDocument, StandardFonts, rgb, type PDFPage } from 'pdf-lib'

type PhotoEvidence = {
  label: string
  coordinates: string
  capturedAt: string
  bytes?: Uint8Array | null
  mimeType?: string | null
}

type PdfReport = {
  reference: string
  reportDate: string
  plotLabel: string
  address: string
  ownerName: string
  plan: string
  agentName: string
  arrival: string
  photos: PhotoEvidence[]
  checklist: Array<{ label: string; result: string; note?: string | null }>
  flags: Array<{ type: string; description: string }>
  documents: Array<{ label: string; result: string; note?: string | null }>
  amenities: Array<{ label: string; condition: string; note?: string | null }>
}

export async function generateInspectionReportPdf(report: PdfReport) {
  const document = await PDFDocument.create()
  const font = await document.embedFont(StandardFonts.Helvetica)
  const bold = await document.embedFont(StandardFonts.HelveticaBold)
  const serif = await document.embedFont(StandardFonts.TimesRomanBold)
  const crimson = rgb(0.753, 0.224, 0.169)
  const muted = rgb(0.4, 0.44, 0.5)
  let page = document.addPage([595, 842])
  let y = 790

  const newPageIfNeeded = (height = 32) => {
    if (y > height + 45) return
    page = document.addPage([595, 842])
    y = 790
  }
  const text = (value: string, size = 10, boldText = false, color = rgb(0.12, 0.16, 0.22)) => {
    newPageIfNeeded(size + 16)
    page.drawText(value.slice(0, 105), { x: 48, y, size, font: boldText ? bold : font, color })
    y -= size + 7
  }
  const heading = (value: string) => {
    newPageIfNeeded(40)
    y -= 8
    page.drawText(value, { x: 48, y, size: 14, font: bold, color: crimson })
    y -= 23
  }

  page.drawRectangle({ x: 48, y: 792, width: 6, height: 28, color: crimson })
  page.drawText('PlotKare', { x: 66, y: 800, size: 22, font: serif, color: rgb(0.12, 0.16, 0.22) })
  page.drawText('VERIFIED FIELD INSPECTION REPORT', { x: 66, y: 787, size: 8, font: bold, color: muted })
  page.drawText(report.reference, { x: 390, y: 800, size: 10, font: bold, color: crimson })
  page.drawText(report.reportDate, { x: 390, y: 786, size: 9, font, color: muted })
  y = 755

  heading('1. Plot Summary')
  text(`Plot: ${report.plotLabel}`, 10, true)
  text(`Address / corridor: ${report.address}`)
  text(`Owner: ${report.ownerName}   Plan: ${report.plan}`)
  text(`Inspection agent: ${report.agentName}   Date: ${report.reportDate}`)
  text(`GPS arrival: ${report.arrival}`)

  heading('2. Evidence Photos')
  for (const photo of report.photos) {
    newPageIfNeeded(175)
    text(`${photo.label} - ${photo.capturedAt}`, 10, true)
    text(photo.coordinates, 9, false, muted)
    if (photo.bytes && (photo.mimeType === 'image/jpeg' || photo.mimeType === 'image/png')) {
      const embedded = photo.mimeType === 'image/png'
        ? await document.embedPng(photo.bytes)
        : await document.embedJpg(photo.bytes)
      const scaled = embedded.scale(0.16)
      const ratio = Math.min(180 / scaled.width, 112 / scaled.height, 1)
      page.drawImage(embedded, { x: 48, y: y - scaled.height * ratio, width: scaled.width * ratio, height: scaled.height * ratio })
      y -= scaled.height * ratio + 12
    }
  }

  heading('3. Boundary Checklist')
  report.checklist.forEach((item) => text(`${item.label}: ${item.result}${item.note ? ` - ${item.note}` : ''}`))

  heading('4. Flags')
  if (!report.flags.length) text('No operational flags recorded.')
  report.flags.forEach((item) => text(`${item.type}: ${item.description}`))

  heading('5. Document Status Summary')
  if (!report.documents.length) text('No document reminders recorded for this plan.')
  report.documents.forEach((item) => text(`${item.label}: ${item.result}${item.note ? ` - ${item.note}` : ''}`))

  heading('6. Amenity Results')
  if (!report.amenities.length) text('No active amenities required inspection.')
  report.amenities.forEach((item) => text(`${item.label}: ${item.condition}${item.note ? ` - ${item.note}` : ''}`))

  newPageIfNeeded(62)
  y -= 18
  page.drawLine({ start: { x: 48, y }, end: { x: 547, y }, thickness: 1, color: rgb(0.9, 0.9, 0.91) })
  y -= 22
  const footer = `This report was generated by PlotKare based on field evidence captured on ${report.reportDate}. GPS coordinates are device-captured location evidence.`
  text(footer, 9, false, muted)
  return document.save()
}
